### ISSUE TITLE
Dependencies expecting a git repository won't build when downloaded as a zip file

### ISSUE THREAD

**Issue by haerfest** [fenollp/erl-mk#14]
The first step to fetch a dependency is to download a zip file, while using git is the fallback.

The [Jiffy JSON parser](https://github.com/davisp/jiffy) has git-specific steps in its Makefile, which won't work when downkoaded as a zip file:

    ERROR: git describe --always --tags failed with error: 128 and output:
    fatal: Not a git repository (or any parent up to mount point /vagrant)
    Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

    ERROR: compile failed while processing deps/jiffy: rebar_abort
    make[1]: *** [build] Error 1

Maybe it's better to give precedence to compatibility over speed and simply always use git?

**Comment by fenollp** [comment]
The quickest workaround I see is checking out the version of erl.mk just previous to these changes: `v2.3`.

In you Makefile just change
```Makefile
erl.mk:
    curl -fsSLo $@ 'https://raw.github.com/fenollp/erl-mk/master/erl.mk' || rm $@
```

to
```Makefile
erl.mk:
    curl -fsSLo $@ 'https://raw.github.com/fenollp/erl-mk/v2.3/erl.mk' || rm $@
```

**Comment by haerfest** [comment]
Thanks, that does indeed work.
